services:
  # バックエンドサービス
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../app:/app/app
      - ../config:/app/config
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DATABASE_URL=mysql://user:password@db:3306/task_manager
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "sleep 10 && flask run --host=0.0.0.0"

  # データベースサービス
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=task_manager
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: 