name: Notion Sync

on:
  schedule:
    - cron: '0 0 * * *'  # UTCなので日本時間9時
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Notion Sync
        run: python scripts/notion_sync.py
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add notion_sync/
          git commit -m "Update Notion sync" || echo "No changes"
          git push
